/**
 * GeoGig Web API
 * GeoGig Web API.  You can find out more about GeoGig at [http://geogig.org](http://geogig.org)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: groldan@boundlessgeo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BoundingBox', 'model/Feature', 'model/FeatureCollection', 'model/FeatureFilter', 'model/FeatureQuery', 'model/LayerInfo', 'model/ObjectHash', 'model/RepoLayerSummary', 'model/RevisionFeatureType', 'model/UpdateFeaturesRequest', 'model/UserLayerSummary'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/BoundingBox'), require('../model/Feature'), require('../model/FeatureCollection'), require('../model/FeatureFilter'), require('../model/FeatureQuery'), require('../model/LayerInfo'), require('../model/ObjectHash'), require('../model/RepoLayerSummary'), require('../model/RevisionFeatureType'), require('../model/UpdateFeaturesRequest'), require('../model/UserLayerSummary'));
  } else {
    // Browser globals (root is window)
    if (!root.Geogig) {
      root.Geogig = {};
    }
    root.Geogig.FeatureServiceApi = factory(root.Geogig.ApiClient, root.Geogig.BoundingBox, root.Geogig.Feature, root.Geogig.FeatureCollection, root.Geogig.FeatureFilter, root.Geogig.FeatureQuery, root.Geogig.LayerInfo, root.Geogig.ObjectHash, root.Geogig.RepoLayerSummary, root.Geogig.RevisionFeatureType, root.Geogig.UpdateFeaturesRequest, root.Geogig.UserLayerSummary);
  }
}(this, function(ApiClient, BoundingBox, Feature, FeatureCollection, FeatureFilter, FeatureQuery, LayerInfo, ObjectHash, RepoLayerSummary, RevisionFeatureType, UpdateFeaturesRequest, UserLayerSummary) {
  'use strict';

  /**
   * FeatureService service.
   * @module api/FeatureServiceApi
   * @version 0.1-SNAPSHOT
   */

  /**
   * Constructs a new FeatureServiceApi. 
   * @alias module:api/FeatureServiceApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Iserts features to this collection in the WORK_HEAD. Parameter features can be either a Feature or a FeatureCollection.
     * The features are added to the WORK_HEAD tree. This operation works against the currently checked out branch for the indicated transaction, and does not perform a geogig commit on its own. The geogig commit is created either manually or once the geogig transaction is committed.
     * @param {String} user repository login owner
     * @param {String} repo repository name
     * @param {String} layer layer name for feature service
     * @param {String} geogigTransactionId transaction identifier, required
     * @param {Object} opts Optional parameters
     * @param {module:model/Feature} opts.features 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.addFeaturesWithHttpInfo = function(user, repo, layer, geogigTransactionId, opts) {
      opts = opts || {};
      var postBody = opts['features'];

      // verify the required parameter 'user' is set
      if (user === undefined || user === null) {
        throw new Error("Missing the required parameter 'user' when calling addFeatures");
      }

      // verify the required parameter 'repo' is set
      if (repo === undefined || repo === null) {
        throw new Error("Missing the required parameter 'repo' when calling addFeatures");
      }

      // verify the required parameter 'layer' is set
      if (layer === undefined || layer === null) {
        throw new Error("Missing the required parameter 'layer' when calling addFeatures");
      }

      // verify the required parameter 'geogigTransactionId' is set
      if (geogigTransactionId === undefined || geogigTransactionId === null) {
        throw new Error("Missing the required parameter 'geogigTransactionId' when calling addFeatures");
      }


      var pathParams = {
        'user': user,
        'repo': repo,
        'layer': layer
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'geogig-transaction-id': geogigTransactionId
      };
      var formParams = {
      };

      var authNames = ['ApiKeyAuth', 'BasicAuth', 'OAuth2'];
      var contentTypes = ['application/vnd.geo+json', 'application/vnd.geo+smile'];
      var accepts = ['application/json', 'application/x-jackson-smile'];
      var returnType = null;

      return this.apiClient.callApi(
        '/layers/{user}/{repo}/{layer}/features', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Iserts features to this collection in the WORK_HEAD. Parameter features can be either a Feature or a FeatureCollection.
     * The features are added to the WORK_HEAD tree. This operation works against the currently checked out branch for the indicated transaction, and does not perform a geogig commit on its own. The geogig commit is created either manually or once the geogig transaction is committed.
     * @param {String} user repository login owner
     * @param {String} repo repository name
     * @param {String} layer layer name for feature service
     * @param {String} geogigTransactionId transaction identifier, required
     * @param {Object} opts Optional parameters
     * @param {module:model/Feature} opts.features 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.addFeatures = function(user, repo, layer, geogigTransactionId, opts) {
      return this.addFeaturesWithHttpInfo(user, repo, layer, geogigTransactionId, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Create a new layer
     * Creating and populating a new layer are two separate steps. First the layer schema must be created and then the features uploaded.
     * @param {String} user repository login owner
     * @param {String} repo repository name
     * @param {String} geogigTransactionId transaction identifier, required
     * @param {module:model/RevisionFeatureType} featureType FeatureType for the layer
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/LayerInfo} and HTTP response
     */
    this.createLayerWithHttpInfo = function(user, repo, geogigTransactionId, featureType) {
      var postBody = featureType;

      // verify the required parameter 'user' is set
      if (user === undefined || user === null) {
        throw new Error("Missing the required parameter 'user' when calling createLayer");
      }

      // verify the required parameter 'repo' is set
      if (repo === undefined || repo === null) {
        throw new Error("Missing the required parameter 'repo' when calling createLayer");
      }

      // verify the required parameter 'geogigTransactionId' is set
      if (geogigTransactionId === undefined || geogigTransactionId === null) {
        throw new Error("Missing the required parameter 'geogigTransactionId' when calling createLayer");
      }

      // verify the required parameter 'featureType' is set
      if (featureType === undefined || featureType === null) {
        throw new Error("Missing the required parameter 'featureType' when calling createLayer");
      }


      var pathParams = {
        'user': user,
        'repo': repo
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'geogig-transaction-id': geogigTransactionId
      };
      var formParams = {
      };

      var authNames = ['ApiKeyAuth', 'BasicAuth', 'OAuth2'];
      var contentTypes = [];
      var accepts = ['application/json', 'application/x-jackson-smile'];
      var returnType = LayerInfo;

      return this.apiClient.callApi(
        '/layers/{user}/{repo}', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Create a new layer
     * Creating and populating a new layer are two separate steps. First the layer schema must be created and then the features uploaded.
     * @param {String} user repository login owner
     * @param {String} repo repository name
     * @param {String} geogigTransactionId transaction identifier, required
     * @param {module:model/RevisionFeatureType} featureType FeatureType for the layer
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/LayerInfo}
     */
    this.createLayer = function(user, repo, geogigTransactionId, featureType) {
      return this.createLayerWithHttpInfo(user, repo, geogigTransactionId, featureType)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete a single feature at the current transaction&#39;s branch
     * @param {String} user repository login owner
     * @param {String} repo repository name
     * @param {String} layer layer name for feature service
     * @param {String} featureId Feature identifier
     * @param {String} geogigTransactionId transaction identifier, required
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.deleteFeatureWithHttpInfo = function(user, repo, layer, featureId, geogigTransactionId) {
      var postBody = null;

      // verify the required parameter 'user' is set
      if (user === undefined || user === null) {
        throw new Error("Missing the required parameter 'user' when calling deleteFeature");
      }

      // verify the required parameter 'repo' is set
      if (repo === undefined || repo === null) {
        throw new Error("Missing the required parameter 'repo' when calling deleteFeature");
      }

      // verify the required parameter 'layer' is set
      if (layer === undefined || layer === null) {
        throw new Error("Missing the required parameter 'layer' when calling deleteFeature");
      }

      // verify the required parameter 'featureId' is set
      if (featureId === undefined || featureId === null) {
        throw new Error("Missing the required parameter 'featureId' when calling deleteFeature");
      }

      // verify the required parameter 'geogigTransactionId' is set
      if (geogigTransactionId === undefined || geogigTransactionId === null) {
        throw new Error("Missing the required parameter 'geogigTransactionId' when calling deleteFeature");
      }


      var pathParams = {
        'user': user,
        'repo': repo,
        'layer': layer,
        'featureId': featureId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'geogig-transaction-id': geogigTransactionId
      };
      var formParams = {
      };

      var authNames = ['ApiKeyAuth', 'BasicAuth', 'OAuth2'];
      var contentTypes = [];
      var accepts = ['application/json', 'application/x-jackson-smile'];
      var returnType = null;

      return this.apiClient.callApi(
        '/layers/{user}/{repo}/{layer}/features/{featureId}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Delete a single feature at the current transaction&#39;s branch
     * @param {String} user repository login owner
     * @param {String} repo repository name
     * @param {String} layer layer name for feature service
     * @param {String} featureId Feature identifier
     * @param {String} geogigTransactionId transaction identifier, required
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.deleteFeature = function(user, repo, layer, featureId, geogigTransactionId) {
      return this.deleteFeatureWithHttpInfo(user, repo, layer, featureId, geogigTransactionId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete features matching the given query
     * @param {String} user repository login owner
     * @param {String} repo repository name
     * @param {String} layer layer name for feature service
     * @param {String} geogigTransactionId transaction identifier, required
     * @param {Object} opts Optional parameters
     * @param {module:model/FeatureFilter} opts.filter 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.deleteFeaturesWithHttpInfo = function(user, repo, layer, geogigTransactionId, opts) {
      opts = opts || {};
      var postBody = opts['filter'];

      // verify the required parameter 'user' is set
      if (user === undefined || user === null) {
        throw new Error("Missing the required parameter 'user' when calling deleteFeatures");
      }

      // verify the required parameter 'repo' is set
      if (repo === undefined || repo === null) {
        throw new Error("Missing the required parameter 'repo' when calling deleteFeatures");
      }

      // verify the required parameter 'layer' is set
      if (layer === undefined || layer === null) {
        throw new Error("Missing the required parameter 'layer' when calling deleteFeatures");
      }

      // verify the required parameter 'geogigTransactionId' is set
      if (geogigTransactionId === undefined || geogigTransactionId === null) {
        throw new Error("Missing the required parameter 'geogigTransactionId' when calling deleteFeatures");
      }


      var pathParams = {
        'user': user,
        'repo': repo,
        'layer': layer
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'geogig-transaction-id': geogigTransactionId
      };
      var formParams = {
      };

      var authNames = ['ApiKeyAuth', 'BasicAuth', 'OAuth2'];
      var contentTypes = [];
      var accepts = ['application/json', 'application/x-jackson-smile'];
      var returnType = null;

      return this.apiClient.callApi(
        '/layers/{user}/{repo}/{layer}/rpc/delete', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Delete features matching the given query
     * @param {String} user repository login owner
     * @param {String} repo repository name
     * @param {String} layer layer name for feature service
     * @param {String} geogigTransactionId transaction identifier, required
     * @param {Object} opts Optional parameters
     * @param {module:model/FeatureFilter} opts.filter 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.deleteFeatures = function(user, repo, layer, geogigTransactionId, opts) {
      return this.deleteFeaturesWithHttpInfo(user, repo, layer, geogigTransactionId, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete a Layer from a repository at the current transaction&#39;s branch
     * @param {String} user repository login owner
     * @param {String} repo repository name
     * @param {String} layer layer name for feature service
     * @param {String} geogigTransactionId transaction identifier, required
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.deleteLayerWithHttpInfo = function(user, repo, layer, geogigTransactionId) {
      var postBody = null;

      // verify the required parameter 'user' is set
      if (user === undefined || user === null) {
        throw new Error("Missing the required parameter 'user' when calling deleteLayer");
      }

      // verify the required parameter 'repo' is set
      if (repo === undefined || repo === null) {
        throw new Error("Missing the required parameter 'repo' when calling deleteLayer");
      }

      // verify the required parameter 'layer' is set
      if (layer === undefined || layer === null) {
        throw new Error("Missing the required parameter 'layer' when calling deleteLayer");
      }

      // verify the required parameter 'geogigTransactionId' is set
      if (geogigTransactionId === undefined || geogigTransactionId === null) {
        throw new Error("Missing the required parameter 'geogigTransactionId' when calling deleteLayer");
      }


      var pathParams = {
        'user': user,
        'repo': repo,
        'layer': layer
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'geogig-transaction-id': geogigTransactionId
      };
      var formParams = {
      };

      var authNames = ['ApiKeyAuth', 'BasicAuth', 'OAuth2'];
      var contentTypes = [];
      var accepts = ['application/json', 'application/x-jackson-smile'];
      var returnType = null;

      return this.apiClient.callApi(
        '/layers/{user}/{repo}/{layer}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Delete a Layer from a repository at the current transaction&#39;s branch
     * @param {String} user repository login owner
     * @param {String} repo repository name
     * @param {String} layer layer name for feature service
     * @param {String} geogigTransactionId transaction identifier, required
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.deleteLayer = function(user, repo, layer, geogigTransactionId) {
      return this.deleteLayerWithHttpInfo(user, repo, layer, geogigTransactionId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get layer bounds at the specified transaction/head. If no head is specified, defaults to WORK_HEAD
     * @param {String} user repository login owner
     * @param {String} repo repository name
     * @param {String} layer layer name for feature service
     * @param {Object} opts Optional parameters
     * @param {String} opts.head a refSpec string leading to a root RevTree (default to WORK_HEAD)
     * @param {String} opts.geogigTransactionId Optional transaction identifier
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/BoundingBox} and HTTP response
     */
    this.getBoundsWithHttpInfo = function(user, repo, layer, opts) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'user' is set
      if (user === undefined || user === null) {
        throw new Error("Missing the required parameter 'user' when calling getBounds");
      }

      // verify the required parameter 'repo' is set
      if (repo === undefined || repo === null) {
        throw new Error("Missing the required parameter 'repo' when calling getBounds");
      }

      // verify the required parameter 'layer' is set
      if (layer === undefined || layer === null) {
        throw new Error("Missing the required parameter 'layer' when calling getBounds");
      }


      var pathParams = {
        'user': user,
        'repo': repo,
        'layer': layer
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'head': opts['head'],
        'geogig-transaction-id': opts['geogigTransactionId']
      };
      var formParams = {
      };

      var authNames = ['ApiKeyAuth', 'BasicAuth', 'OAuth2'];
      var contentTypes = [];
      var accepts = ['application/json', 'application/x-jackson-smile'];
      var returnType = BoundingBox;

      return this.apiClient.callApi(
        '/layers/{user}/{repo}/{layer}/bounds', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get layer bounds at the specified transaction/head. If no head is specified, defaults to WORK_HEAD
     * @param {String} user repository login owner
     * @param {String} repo repository name
     * @param {String} layer layer name for feature service
     * @param {Object} opts Optional parameters
     * @param {String} opts.head a refSpec string leading to a root RevTree (default to WORK_HEAD)
     * @param {String} opts.geogigTransactionId Optional transaction identifier
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/BoundingBox}
     */
    this.getBounds = function(user, repo, layer, opts) {
      return this.getBoundsWithHttpInfo(user, repo, layer, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get a single feature from a layer given its feature id, at the specified transaction/head
     * @param {String} user repository login owner
     * @param {String} repo repository name
     * @param {String} layer layer name for feature service
     * @param {String} featureId Feature identifier
     * @param {Object} opts Optional parameters
     * @param {String} opts.head a refSpec string leading to a root RevTree (default to WORK_HEAD)
     * @param {String} opts.geogigTransactionId Optional transaction identifier
     * @param {String} opts.ifNoneMatch Conditional get, return feature its revision feature hash does not match the provided hash
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Feature} and HTTP response
     */
    this.getFeatureWithHttpInfo = function(user, repo, layer, featureId, opts) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'user' is set
      if (user === undefined || user === null) {
        throw new Error("Missing the required parameter 'user' when calling getFeature");
      }

      // verify the required parameter 'repo' is set
      if (repo === undefined || repo === null) {
        throw new Error("Missing the required parameter 'repo' when calling getFeature");
      }

      // verify the required parameter 'layer' is set
      if (layer === undefined || layer === null) {
        throw new Error("Missing the required parameter 'layer' when calling getFeature");
      }

      // verify the required parameter 'featureId' is set
      if (featureId === undefined || featureId === null) {
        throw new Error("Missing the required parameter 'featureId' when calling getFeature");
      }


      var pathParams = {
        'user': user,
        'repo': repo,
        'layer': layer,
        'featureId': featureId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'head': opts['head'],
        'geogig-transaction-id': opts['geogigTransactionId'],
        'If-None-Match': opts['ifNoneMatch']
      };
      var formParams = {
      };

      var authNames = ['ApiKeyAuth', 'BasicAuth', 'OAuth2'];
      var contentTypes = [];
      var accepts = ['application/vnd.geo+json', 'application/vnd.geo+smile'];
      var returnType = Feature;

      return this.apiClient.callApi(
        '/layers/{user}/{repo}/{layer}/features/{featureId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get a single feature from a layer given its feature id, at the specified transaction/head
     * @param {String} user repository login owner
     * @param {String} repo repository name
     * @param {String} layer layer name for feature service
     * @param {String} featureId Feature identifier
     * @param {Object} opts Optional parameters
     * @param {String} opts.head a refSpec string leading to a root RevTree (default to WORK_HEAD)
     * @param {String} opts.geogigTransactionId Optional transaction identifier
     * @param {String} opts.ifNoneMatch Conditional get, return feature its revision feature hash does not match the provided hash
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Feature}
     */
    this.getFeature = function(user, repo, layer, featureId, opts) {
      return this.getFeatureWithHttpInfo(user, repo, layer, featureId, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get Features from a geogig Layer
     * Obtain a stream of features from a geogig layer at the specified transaction/head
     * @param {String} user repository login owner
     * @param {String} repo repository name
     * @param {String} layer layer name for feature service
     * @param {Object} opts Optional parameters
     * @param {Array.<Number>} opts.bbox Comma separated values for a query bounding box in minx,miny,maxx,maxy format. Example: ?bbox&#x3D;-180,-90,180,90
     * @param {Array.<String>} opts.attributes Ordered list of attribute names to return
     * @param {String} opts.head a refSpec string leading to a root RevTree (default to WORK_HEAD)
     * @param {String} opts.geogigTransactionId Optional transaction identifier
     * @param {Number} opts.page Page number to retrive when requesting collections, starts at 1.
     * @param {Number} opts.pageSize number of elements to return in a paging query. If page is specified and pageSize is not, pageSize defaults to 100. If pageSize is specified, page becomes mandatory
     * @param {String} opts.ifNoneMatch Conditional get, return features if the layer tree does not match the provided hash
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/FeatureCollection} and HTTP response
     */
    this.getFeaturesWithHttpInfo = function(user, repo, layer, opts) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'user' is set
      if (user === undefined || user === null) {
        throw new Error("Missing the required parameter 'user' when calling getFeatures");
      }

      // verify the required parameter 'repo' is set
      if (repo === undefined || repo === null) {
        throw new Error("Missing the required parameter 'repo' when calling getFeatures");
      }

      // verify the required parameter 'layer' is set
      if (layer === undefined || layer === null) {
        throw new Error("Missing the required parameter 'layer' when calling getFeatures");
      }


      var pathParams = {
        'user': user,
        'repo': repo,
        'layer': layer
      };
      var queryParams = {
        'page': opts['page'],
        'pageSize': opts['pageSize'],
      };
      var collectionQueryParams = {
        'bbox': {
          value: opts['bbox'],
          collectionFormat: 'csv'
        },
        'attributes': {
          value: opts['attributes'],
          collectionFormat: 'csv'
        },
      };
      var headerParams = {
        'head': opts['head'],
        'geogig-transaction-id': opts['geogigTransactionId'],
        'If-None-Match': opts['ifNoneMatch']
      };
      var formParams = {
      };

      var authNames = ['ApiKeyAuth', 'BasicAuth', 'OAuth2'];
      var contentTypes = [];
      var accepts = ['application/vnd.geo+json', 'application/vnd.geo+smile', 'application/vnd.geogig.features+json', 'application/vnd.geogig.features+smile'];
      var returnType = FeatureCollection;

      return this.apiClient.callApi(
        '/layers/{user}/{repo}/{layer}/features', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get Features from a geogig Layer
     * Obtain a stream of features from a geogig layer at the specified transaction/head
     * @param {String} user repository login owner
     * @param {String} repo repository name
     * @param {String} layer layer name for feature service
     * @param {Object} opts Optional parameters
     * @param {Array.<Number>} opts.bbox Comma separated values for a query bounding box in minx,miny,maxx,maxy format. Example: ?bbox&#x3D;-180,-90,180,90
     * @param {Array.<String>} opts.attributes Ordered list of attribute names to return
     * @param {String} opts.head a refSpec string leading to a root RevTree (default to WORK_HEAD)
     * @param {String} opts.geogigTransactionId Optional transaction identifier
     * @param {Number} opts.page Page number to retrive when requesting collections, starts at 1.
     * @param {Number} opts.pageSize number of elements to return in a paging query. If page is specified and pageSize is not, pageSize defaults to 100. If pageSize is specified, page becomes mandatory
     * @param {String} opts.ifNoneMatch Conditional get, return features if the layer tree does not match the provided hash
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/FeatureCollection}
     */
    this.getFeatures = function(user, repo, layer, opts) {
      return this.getFeaturesWithHttpInfo(user, repo, layer, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get a unique identifier for the current state of the layer.
     * Get a unique identifier for the current state of the layer. Any change/edit to the layer will change this identifier. This operation can be used to verify whether the layer has changed since the client last accessed it.
     * @param {String} user repository login owner
     * @param {String} repo repository name
     * @param {String} layer layer name for feature service
     * @param {Object} opts Optional parameters
     * @param {String} opts.head a refSpec string leading to a root RevTree (default to WORK_HEAD)
     * @param {String} opts.geogigTransactionId Optional transaction identifier
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ObjectHash} and HTTP response
     */
    this.getLayerHashWithHttpInfo = function(user, repo, layer, opts) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'user' is set
      if (user === undefined || user === null) {
        throw new Error("Missing the required parameter 'user' when calling getLayerHash");
      }

      // verify the required parameter 'repo' is set
      if (repo === undefined || repo === null) {
        throw new Error("Missing the required parameter 'repo' when calling getLayerHash");
      }

      // verify the required parameter 'layer' is set
      if (layer === undefined || layer === null) {
        throw new Error("Missing the required parameter 'layer' when calling getLayerHash");
      }


      var pathParams = {
        'user': user,
        'repo': repo,
        'layer': layer
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'head': opts['head'],
        'geogig-transaction-id': opts['geogigTransactionId']
      };
      var formParams = {
      };

      var authNames = ['ApiKeyAuth', 'BasicAuth', 'OAuth2'];
      var contentTypes = [];
      var accepts = ['application/json', 'text/plain'];
      var returnType = ObjectHash;

      return this.apiClient.callApi(
        '/layers/{user}/{repo}/{layer}', 'HEAD',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get a unique identifier for the current state of the layer.
     * Get a unique identifier for the current state of the layer. Any change/edit to the layer will change this identifier. This operation can be used to verify whether the layer has changed since the client last accessed it.
     * @param {String} user repository login owner
     * @param {String} repo repository name
     * @param {String} layer layer name for feature service
     * @param {Object} opts Optional parameters
     * @param {String} opts.head a refSpec string leading to a root RevTree (default to WORK_HEAD)
     * @param {String} opts.geogigTransactionId Optional transaction identifier
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ObjectHash}
     */
    this.getLayerHash = function(user, repo, layer, opts) {
      return this.getLayerHashWithHttpInfo(user, repo, layer, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get layer metadata at the specified transaction/head
     * @param {String} user repository login owner
     * @param {String} repo repository name
     * @param {String} layer layer name for feature service
     * @param {Object} opts Optional parameters
     * @param {String} opts.head a refSpec string leading to a root RevTree (default to WORK_HEAD)
     * @param {String} opts.geogigTransactionId Optional transaction identifier
     * @param {String} opts.ifNoneMatch Conditional get, layer info if its revision tree hash does not match the provided hash
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/LayerInfo} and HTTP response
     */
    this.getLayerInfoWithHttpInfo = function(user, repo, layer, opts) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'user' is set
      if (user === undefined || user === null) {
        throw new Error("Missing the required parameter 'user' when calling getLayerInfo");
      }

      // verify the required parameter 'repo' is set
      if (repo === undefined || repo === null) {
        throw new Error("Missing the required parameter 'repo' when calling getLayerInfo");
      }

      // verify the required parameter 'layer' is set
      if (layer === undefined || layer === null) {
        throw new Error("Missing the required parameter 'layer' when calling getLayerInfo");
      }


      var pathParams = {
        'user': user,
        'repo': repo,
        'layer': layer
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'head': opts['head'],
        'geogig-transaction-id': opts['geogigTransactionId'],
        'If-None-Match': opts['ifNoneMatch']
      };
      var formParams = {
      };

      var authNames = ['ApiKeyAuth', 'BasicAuth', 'OAuth2'];
      var contentTypes = [];
      var accepts = ['application/json', 'application/x-jackson-smile'];
      var returnType = LayerInfo;

      return this.apiClient.callApi(
        '/layers/{user}/{repo}/{layer}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get layer metadata at the specified transaction/head
     * @param {String} user repository login owner
     * @param {String} repo repository name
     * @param {String} layer layer name for feature service
     * @param {Object} opts Optional parameters
     * @param {String} opts.head a refSpec string leading to a root RevTree (default to WORK_HEAD)
     * @param {String} opts.geogigTransactionId Optional transaction identifier
     * @param {String} opts.ifNoneMatch Conditional get, layer info if its revision tree hash does not match the provided hash
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/LayerInfo}
     */
    this.getLayerInfo = function(user, repo, layer, opts) {
      return this.getLayerInfoWithHttpInfo(user, repo, layer, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * return a summary of layers per user
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/UserLayerSummary>} and HTTP response
     */
    this.getLayersSummariesWithHttpInfo = function() {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['ApiKeyAuth', 'BasicAuth', 'OAuth2'];
      var contentTypes = [];
      var accepts = ['application/json', 'application/x-jackson-smile'];
      var returnType = [UserLayerSummary];

      return this.apiClient.callApi(
        '/layers', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * return a summary of layers per user
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/UserLayerSummary>}
     */
    this.getLayersSummaries = function() {
      return this.getLayersSummariesWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get Layer schema
     * Get layer&#39;s Feature Type at the specified transaction/head. If no head is specified, defaults to WORK_HEAD
     * @param {String} user repository login owner
     * @param {String} repo repository name
     * @param {String} layer layer name for feature service
     * @param {Object} opts Optional parameters
     * @param {String} opts.head a refSpec string leading to a root RevTree (default to WORK_HEAD)
     * @param {String} opts.geogigTransactionId Optional transaction identifier
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/RevisionFeatureType} and HTTP response
     */
    this.getSchemaWithHttpInfo = function(user, repo, layer, opts) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'user' is set
      if (user === undefined || user === null) {
        throw new Error("Missing the required parameter 'user' when calling getSchema");
      }

      // verify the required parameter 'repo' is set
      if (repo === undefined || repo === null) {
        throw new Error("Missing the required parameter 'repo' when calling getSchema");
      }

      // verify the required parameter 'layer' is set
      if (layer === undefined || layer === null) {
        throw new Error("Missing the required parameter 'layer' when calling getSchema");
      }


      var pathParams = {
        'user': user,
        'repo': repo,
        'layer': layer
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'head': opts['head'],
        'geogig-transaction-id': opts['geogigTransactionId']
      };
      var formParams = {
      };

      var authNames = ['ApiKeyAuth', 'BasicAuth', 'OAuth2'];
      var contentTypes = [];
      var accepts = ['application/json', 'application/x-jackson-smile'];
      var returnType = RevisionFeatureType;

      return this.apiClient.callApi(
        '/layers/{user}/{repo}/{layer}/schema', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get Layer schema
     * Get layer&#39;s Feature Type at the specified transaction/head. If no head is specified, defaults to WORK_HEAD
     * @param {String} user repository login owner
     * @param {String} repo repository name
     * @param {String} layer layer name for feature service
     * @param {Object} opts Optional parameters
     * @param {String} opts.head a refSpec string leading to a root RevTree (default to WORK_HEAD)
     * @param {String} opts.geogigTransactionId Optional transaction identifier
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/RevisionFeatureType}
     */
    this.getSchema = function(user, repo, layer, opts) {
      return this.getSchemaWithHttpInfo(user, repo, layer, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get layer&#39;s number of features at the specified transaction/head. If no head is specified, defaults to WORK_HEAD
     * @param {String} user repository login owner
     * @param {String} repo repository name
     * @param {String} layer layer name for feature service
     * @param {Object} opts Optional parameters
     * @param {String} opts.head a refSpec string leading to a root RevTree (default to WORK_HEAD)
     * @param {String} opts.geogigTransactionId Optional transaction identifier
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link 'Number'} and HTTP response
     */
    this.getSizeWithHttpInfo = function(user, repo, layer, opts) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'user' is set
      if (user === undefined || user === null) {
        throw new Error("Missing the required parameter 'user' when calling getSize");
      }

      // verify the required parameter 'repo' is set
      if (repo === undefined || repo === null) {
        throw new Error("Missing the required parameter 'repo' when calling getSize");
      }

      // verify the required parameter 'layer' is set
      if (layer === undefined || layer === null) {
        throw new Error("Missing the required parameter 'layer' when calling getSize");
      }


      var pathParams = {
        'user': user,
        'repo': repo,
        'layer': layer
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'head': opts['head'],
        'geogig-transaction-id': opts['geogigTransactionId']
      };
      var formParams = {
      };

      var authNames = ['ApiKeyAuth', 'BasicAuth', 'OAuth2'];
      var contentTypes = [];
      var accepts = ['application/json', 'application/x-jackson-smile'];
      var returnType = 'Number';

      return this.apiClient.callApi(
        '/layers/{user}/{repo}/{layer}/size', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get layer&#39;s number of features at the specified transaction/head. If no head is specified, defaults to WORK_HEAD
     * @param {String} user repository login owner
     * @param {String} repo repository name
     * @param {String} layer layer name for feature service
     * @param {Object} opts Optional parameters
     * @param {String} opts.head a refSpec string leading to a root RevTree (default to WORK_HEAD)
     * @param {String} opts.geogigTransactionId Optional transaction identifier
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link 'Number'}
     */
    this.getSize = function(user, repo, layer, opts) {
      return this.getSizeWithHttpInfo(user, repo, layer, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * return a summary of this user&#39;s layers
     * @param {String} user repository login owner
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/RepoLayerSummary>} and HTTP response
     */
    this.getUserLayersSummariesWithHttpInfo = function(user) {
      var postBody = null;

      // verify the required parameter 'user' is set
      if (user === undefined || user === null) {
        throw new Error("Missing the required parameter 'user' when calling getUserLayersSummaries");
      }


      var pathParams = {
        'user': user
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['ApiKeyAuth', 'BasicAuth', 'OAuth2'];
      var contentTypes = [];
      var accepts = ['application/json', 'application/x-jackson-smile'];
      var returnType = [RepoLayerSummary];

      return this.apiClient.callApi(
        '/layers/{user}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * return a summary of this user&#39;s layers
     * @param {String} user repository login owner
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/RepoLayerSummary>}
     */
    this.getUserLayersSummaries = function(user) {
      return this.getUserLayersSummariesWithHttpInfo(user)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * List layers in a repo
     * List the available layers in the requested [transaction]/repository/[head]
     * @param {String} user repository login owner
     * @param {String} repo repository name
     * @param {Object} opts Optional parameters
     * @param {String} opts.geogigTransactionId Optional transaction identifier
     * @param {String} opts.head a refSpec string leading to a root RevTree (default to WORK_HEAD)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/LayerInfo>} and HTTP response
     */
    this.listLayersWithHttpInfo = function(user, repo, opts) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'user' is set
      if (user === undefined || user === null) {
        throw new Error("Missing the required parameter 'user' when calling listLayers");
      }

      // verify the required parameter 'repo' is set
      if (repo === undefined || repo === null) {
        throw new Error("Missing the required parameter 'repo' when calling listLayers");
      }


      var pathParams = {
        'user': user,
        'repo': repo
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'geogig-transaction-id': opts['geogigTransactionId'],
        'head': opts['head']
      };
      var formParams = {
      };

      var authNames = ['ApiKeyAuth', 'BasicAuth', 'OAuth2'];
      var contentTypes = [];
      var accepts = ['application/json', 'application/x-jackson-smile'];
      var returnType = [LayerInfo];

      return this.apiClient.callApi(
        '/layers/{user}/{repo}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * List layers in a repo
     * List the available layers in the requested [transaction]/repository/[head]
     * @param {String} user repository login owner
     * @param {String} repo repository name
     * @param {Object} opts Optional parameters
     * @param {String} opts.geogigTransactionId Optional transaction identifier
     * @param {String} opts.head a refSpec string leading to a root RevTree (default to WORK_HEAD)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/LayerInfo>}
     */
    this.listLayers = function(user, repo, opts) {
      return this.listLayersWithHttpInfo(user, repo, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Replace a single feature at the current transaction&#39;s branch
     * @param {String} user repository login owner
     * @param {String} repo repository name
     * @param {String} layer layer name for feature service
     * @param {String} featureId Feature identifier
     * @param {String} geogigTransactionId transaction identifier, required
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.modifyFeatureWithHttpInfo = function(user, repo, layer, featureId, geogigTransactionId) {
      var postBody = null;

      // verify the required parameter 'user' is set
      if (user === undefined || user === null) {
        throw new Error("Missing the required parameter 'user' when calling modifyFeature");
      }

      // verify the required parameter 'repo' is set
      if (repo === undefined || repo === null) {
        throw new Error("Missing the required parameter 'repo' when calling modifyFeature");
      }

      // verify the required parameter 'layer' is set
      if (layer === undefined || layer === null) {
        throw new Error("Missing the required parameter 'layer' when calling modifyFeature");
      }

      // verify the required parameter 'featureId' is set
      if (featureId === undefined || featureId === null) {
        throw new Error("Missing the required parameter 'featureId' when calling modifyFeature");
      }

      // verify the required parameter 'geogigTransactionId' is set
      if (geogigTransactionId === undefined || geogigTransactionId === null) {
        throw new Error("Missing the required parameter 'geogigTransactionId' when calling modifyFeature");
      }


      var pathParams = {
        'user': user,
        'repo': repo,
        'layer': layer,
        'featureId': featureId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'geogig-transaction-id': geogigTransactionId
      };
      var formParams = {
      };

      var authNames = ['ApiKeyAuth', 'BasicAuth', 'OAuth2'];
      var contentTypes = ['application/vnd.geo+json'];
      var accepts = ['application/json', 'application/x-jackson-smile'];
      var returnType = null;

      return this.apiClient.callApi(
        '/layers/{user}/{repo}/{layer}/features/{featureId}', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Replace a single feature at the current transaction&#39;s branch
     * @param {String} user repository login owner
     * @param {String} repo repository name
     * @param {String} layer layer name for feature service
     * @param {String} featureId Feature identifier
     * @param {String} geogigTransactionId transaction identifier, required
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.modifyFeature = function(user, repo, layer, featureId, geogigTransactionId) {
      return this.modifyFeatureWithHttpInfo(user, repo, layer, featureId, geogigTransactionId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Modifies features matching the given query with the given values, in the WORK_HEAD of the currently checked out branch for the indicated transaction
     * The features are looked up and modifies in current  WORK_HEAD tree. This operation works against the currently checked out branch for the indicated transaction, and does not perform a geogig commit on its own. The geogig commit is created either manually or once the geogig transaction is committed.
     * @param {String} user repository login owner
     * @param {String} repo repository name
     * @param {String} layer layer name for feature service
     * @param {String} geogigTransactionId transaction identifier, required
     * @param {Object} opts Optional parameters
     * @param {module:model/UpdateFeaturesRequest} opts.query 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.modifyFeaturesWithHttpInfo = function(user, repo, layer, geogigTransactionId, opts) {
      opts = opts || {};
      var postBody = opts['query'];

      // verify the required parameter 'user' is set
      if (user === undefined || user === null) {
        throw new Error("Missing the required parameter 'user' when calling modifyFeatures");
      }

      // verify the required parameter 'repo' is set
      if (repo === undefined || repo === null) {
        throw new Error("Missing the required parameter 'repo' when calling modifyFeatures");
      }

      // verify the required parameter 'layer' is set
      if (layer === undefined || layer === null) {
        throw new Error("Missing the required parameter 'layer' when calling modifyFeatures");
      }

      // verify the required parameter 'geogigTransactionId' is set
      if (geogigTransactionId === undefined || geogigTransactionId === null) {
        throw new Error("Missing the required parameter 'geogigTransactionId' when calling modifyFeatures");
      }


      var pathParams = {
        'user': user,
        'repo': repo,
        'layer': layer
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'geogig-transaction-id': geogigTransactionId
      };
      var formParams = {
      };

      var authNames = ['ApiKeyAuth', 'BasicAuth', 'OAuth2'];
      var contentTypes = [];
      var accepts = ['application/json', 'application/x-jackson-smile'];
      var returnType = null;

      return this.apiClient.callApi(
        '/layers/{user}/{repo}/{layer}/rpc/update', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Modifies features matching the given query with the given values, in the WORK_HEAD of the currently checked out branch for the indicated transaction
     * The features are looked up and modifies in current  WORK_HEAD tree. This operation works against the currently checked out branch for the indicated transaction, and does not perform a geogig commit on its own. The geogig commit is created either manually or once the geogig transaction is committed.
     * @param {String} user repository login owner
     * @param {String} repo repository name
     * @param {String} layer layer name for feature service
     * @param {String} geogigTransactionId transaction identifier, required
     * @param {Object} opts Optional parameters
     * @param {module:model/UpdateFeaturesRequest} opts.query 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.modifyFeatures = function(user, repo, layer, geogigTransactionId, opts) {
      return this.modifyFeaturesWithHttpInfo(user, repo, layer, geogigTransactionId, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Query and return features of this layer tha match the specified FeatureQuery
     * The features are looked up WORK_HEAD tree unless the head parameter has been provided.
     * @param {String} user repository login owner
     * @param {String} repo repository name
     * @param {String} layer layer name for feature service
     * @param {Object} opts Optional parameters
     * @param {module:model/FeatureQuery} opts.query 
     * @param {String} opts.geogigTransactionId Optional transaction identifier
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/FeatureCollection} and HTTP response
     */
    this.queryFeaturesWithHttpInfo = function(user, repo, layer, opts) {
      opts = opts || {};
      var postBody = opts['query'];

      // verify the required parameter 'user' is set
      if (user === undefined || user === null) {
        throw new Error("Missing the required parameter 'user' when calling queryFeatures");
      }

      // verify the required parameter 'repo' is set
      if (repo === undefined || repo === null) {
        throw new Error("Missing the required parameter 'repo' when calling queryFeatures");
      }

      // verify the required parameter 'layer' is set
      if (layer === undefined || layer === null) {
        throw new Error("Missing the required parameter 'layer' when calling queryFeatures");
      }


      var pathParams = {
        'user': user,
        'repo': repo,
        'layer': layer
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'geogig-transaction-id': opts['geogigTransactionId']
      };
      var formParams = {
      };

      var authNames = ['ApiKeyAuth', 'BasicAuth', 'OAuth2'];
      var contentTypes = [];
      var accepts = ['application/vnd.geo+json', 'application/vnd.geo+smile', 'application/vnd.geogig.features+json', 'application/vnd.geogig.features+smile'];
      var returnType = FeatureCollection;

      return this.apiClient.callApi(
        '/layers/{user}/{repo}/{layer}/rpc/query', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Query and return features of this layer tha match the specified FeatureQuery
     * The features are looked up WORK_HEAD tree unless the head parameter has been provided.
     * @param {String} user repository login owner
     * @param {String} repo repository name
     * @param {String} layer layer name for feature service
     * @param {Object} opts Optional parameters
     * @param {module:model/FeatureQuery} opts.query 
     * @param {String} opts.geogigTransactionId Optional transaction identifier
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/FeatureCollection}
     */
    this.queryFeatures = function(user, repo, layer, opts) {
      return this.queryFeaturesWithHttpInfo(user, repo, layer, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Deletes all features in the layer
     * @param {String} user repository login owner
     * @param {String} repo repository name
     * @param {String} layer layer name for feature service
     * @param {String} geogigTransactionId transaction identifier, required
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.truncateWithHttpInfo = function(user, repo, layer, geogigTransactionId) {
      var postBody = null;

      // verify the required parameter 'user' is set
      if (user === undefined || user === null) {
        throw new Error("Missing the required parameter 'user' when calling truncate");
      }

      // verify the required parameter 'repo' is set
      if (repo === undefined || repo === null) {
        throw new Error("Missing the required parameter 'repo' when calling truncate");
      }

      // verify the required parameter 'layer' is set
      if (layer === undefined || layer === null) {
        throw new Error("Missing the required parameter 'layer' when calling truncate");
      }

      // verify the required parameter 'geogigTransactionId' is set
      if (geogigTransactionId === undefined || geogigTransactionId === null) {
        throw new Error("Missing the required parameter 'geogigTransactionId' when calling truncate");
      }


      var pathParams = {
        'user': user,
        'repo': repo,
        'layer': layer
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'geogig-transaction-id': geogigTransactionId
      };
      var formParams = {
      };

      var authNames = ['ApiKeyAuth', 'BasicAuth', 'OAuth2'];
      var contentTypes = [];
      var accepts = ['application/json', 'application/x-jackson-smile'];
      var returnType = null;

      return this.apiClient.callApi(
        '/layers/{user}/{repo}/{layer}/features', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Deletes all features in the layer
     * @param {String} user repository login owner
     * @param {String} repo repository name
     * @param {String} layer layer name for feature service
     * @param {String} geogigTransactionId transaction identifier, required
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.truncate = function(user, repo, layer, geogigTransactionId) {
      return this.truncateWithHttpInfo(user, repo, layer, geogigTransactionId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Change Layer schema. Must be called inside a transaction.
     * Modify the layer&#39;s number of features at the specified transaction/head. If no head is specified, defaults to WORK_HEAD
     * @param {String} user repository login owner
     * @param {String} repo repository name
     * @param {String} layer layer name for feature service
     * @param {String} geogigTransactionId transaction identifier, required
     * @param {module:model/RevisionFeatureType} featureType FeatureType for the layer
     * @param {Object} opts Optional parameters
     * @param {String} opts.head a refSpec string leading to a root RevTree (default to WORK_HEAD)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/RevisionFeatureType} and HTTP response
     */
    this.updateSchemaWithHttpInfo = function(user, repo, layer, geogigTransactionId, featureType, opts) {
      opts = opts || {};
      var postBody = featureType;

      // verify the required parameter 'user' is set
      if (user === undefined || user === null) {
        throw new Error("Missing the required parameter 'user' when calling updateSchema");
      }

      // verify the required parameter 'repo' is set
      if (repo === undefined || repo === null) {
        throw new Error("Missing the required parameter 'repo' when calling updateSchema");
      }

      // verify the required parameter 'layer' is set
      if (layer === undefined || layer === null) {
        throw new Error("Missing the required parameter 'layer' when calling updateSchema");
      }

      // verify the required parameter 'geogigTransactionId' is set
      if (geogigTransactionId === undefined || geogigTransactionId === null) {
        throw new Error("Missing the required parameter 'geogigTransactionId' when calling updateSchema");
      }

      // verify the required parameter 'featureType' is set
      if (featureType === undefined || featureType === null) {
        throw new Error("Missing the required parameter 'featureType' when calling updateSchema");
      }


      var pathParams = {
        'user': user,
        'repo': repo,
        'layer': layer
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'head': opts['head'],
        'geogig-transaction-id': geogigTransactionId
      };
      var formParams = {
      };

      var authNames = ['ApiKeyAuth', 'BasicAuth', 'OAuth2'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json', 'application/x-jackson-smile'];
      var returnType = RevisionFeatureType;

      return this.apiClient.callApi(
        '/layers/{user}/{repo}/{layer}/schema', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Change Layer schema. Must be called inside a transaction.
     * Modify the layer&#39;s number of features at the specified transaction/head. If no head is specified, defaults to WORK_HEAD
     * @param {String} user repository login owner
     * @param {String} repo repository name
     * @param {String} layer layer name for feature service
     * @param {String} geogigTransactionId transaction identifier, required
     * @param {module:model/RevisionFeatureType} featureType FeatureType for the layer
     * @param {Object} opts Optional parameters
     * @param {String} opts.head a refSpec string leading to a root RevTree (default to WORK_HEAD)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/RevisionFeatureType}
     */
    this.updateSchema = function(user, repo, layer, geogigTransactionId, featureType, opts) {
      return this.updateSchemaWithHttpInfo(user, repo, layer, geogigTransactionId, featureType, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
