/**
 * GeoGig Web API
 * GeoGig Web API.  You can find out more about GeoGig at [http://geogig.org](http://geogig.org)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: groldan@boundlessgeo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Geogig);
  }
}(this, function(expect, Geogig) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Geogig.PullRequestInfo();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PullRequestInfo', function() {
    it('should create an instance of PullRequestInfo', function() {
      // uncomment below and update the code to test PullRequestInfo
      //var instane = new Geogig.PullRequestInfo();
      //expect(instance).to.be.a(Geogig.PullRequestInfo);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new Geogig.PullRequestInfo();
      //expect(instance).to.be();
    });

    it('should have the property sourceBranch (base name: "sourceBranch")', function() {
      // uncomment below and update the code to test the property sourceBranch
      //var instane = new Geogig.PullRequestInfo();
      //expect(instance).to.be();
    });

    it('should have the property targetBranch (base name: "targetBranch")', function() {
      // uncomment below and update the code to test the property targetBranch
      //var instane = new Geogig.PullRequestInfo();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instane = new Geogig.PullRequestInfo();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new Geogig.PullRequestInfo();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new Geogig.PullRequestInfo();
      //expect(instance).to.be();
    });

    it('should have the property mergeable (base name: "mergeable")', function() {
      // uncomment below and update the code to test the property mergeable
      //var instane = new Geogig.PullRequestInfo();
      //expect(instance).to.be();
    });

    it('should have the property mergeCommit (base name: "merge_commit")', function() {
      // uncomment below and update the code to test the property mergeCommit
      //var instane = new Geogig.PullRequestInfo();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instane = new Geogig.PullRequestInfo();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instane = new Geogig.PullRequestInfo();
      //expect(instance).to.be();
    });

    it('should have the property closedAt (base name: "closed_at")', function() {
      // uncomment below and update the code to test the property closedAt
      //var instane = new Geogig.PullRequestInfo();
      //expect(instance).to.be();
    });

    it('should have the property createdBy (base name: "createdBy")', function() {
      // uncomment below and update the code to test the property createdBy
      //var instane = new Geogig.PullRequestInfo();
      //expect(instance).to.be();
    });

    it('should have the property closedBy (base name: "closedBy")', function() {
      // uncomment below and update the code to test the property closedBy
      //var instane = new Geogig.PullRequestInfo();
      //expect(instance).to.be();
    });

    it('should have the property sourceRepo (base name: "sourceRepo")', function() {
      // uncomment below and update the code to test the property sourceRepo
      //var instane = new Geogig.PullRequestInfo();
      //expect(instance).to.be();
    });

    it('should have the property targetRepo (base name: "targetRepo")', function() {
      // uncomment below and update the code to test the property targetRepo
      //var instane = new Geogig.PullRequestInfo();
      //expect(instance).to.be();
    });

  });

}));
