/**
 * GeoGig Web API
 * GeoGig Web API.  You can find out more about GeoGig at [http://geogig.org](http://geogig.org)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: groldan@boundlessgeo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Geogig);
  }
}(this, function(expect, Geogig) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Geogig.UserInfoPrivateProfile();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserInfoPrivateProfile', function() {
    it('should create an instance of UserInfoPrivateProfile', function() {
      // uncomment below and update the code to test UserInfoPrivateProfile
      //var instane = new Geogig.UserInfoPrivateProfile();
      //expect(instance).to.be.a(Geogig.UserInfoPrivateProfile);
    });

    it('should have the property fullName (base name: "fullName")', function() {
      // uncomment below and update the code to test the property fullName
      //var instane = new Geogig.UserInfoPrivateProfile();
      //expect(instance).to.be();
    });

    it('should have the property emailAddress (base name: "emailAddress")', function() {
      // uncomment below and update the code to test the property emailAddress
      //var instane = new Geogig.UserInfoPrivateProfile();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instane = new Geogig.UserInfoPrivateProfile();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instane = new Geogig.UserInfoPrivateProfile();
      //expect(instance).to.be();
    });

    it('should have the property location (base name: "location")', function() {
      // uncomment below and update the code to test the property location
      //var instane = new Geogig.UserInfoPrivateProfile();
      //expect(instance).to.be();
    });

    it('should have the property defaultStore (base name: "defaultStore")', function() {
      // uncomment below and update the code to test the property defaultStore
      //var instane = new Geogig.UserInfoPrivateProfile();
      //expect(instance).to.be();
    });

    it('should have the property additionalStores (base name: "additionalStores")', function() {
      // uncomment below and update the code to test the property additionalStores
      //var instane = new Geogig.UserInfoPrivateProfile();
      //expect(instance).to.be();
    });

  });

}));
