/**
 * GeoGig Web API
 * GeoGig Web API.  You can find out more about GeoGig at [http://geogig.org](http://geogig.org)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: groldan@boundlessgeo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['org.geogig.web/ApiClient', 'org.geogig.web/org.geogig.web.model/ObjectType', 'org.geogig.web/org.geogig.web.model/RevisionObject', 'org.geogig.web/org.geogig.web.model/Value'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ObjectType'), require('./RevisionObject'), require('./Value'));
  } else {
    // Browser globals (root is window)
    if (!root.Geogig) {
      root.Geogig = {};
    }
    root.Geogig.RevisionFeature = factory(root.Geogig.ApiClient, root.Geogig.ObjectType, root.Geogig.RevisionObject, root.Geogig.Value);
  }
}(this, function(ApiClient, ObjectType, RevisionObject, Value) {
  'use strict';




  /**
   * The RevisionFeature model module.
   * @module org.geogig.web/org.geogig.web.model/RevisionFeature
   * @version 1.0-SNAPSHOT
   */

  /**
   * Constructs a new <code>RevisionFeature</code>.
   * @alias module:org.geogig.web/org.geogig.web.model/RevisionFeature
   * @class
   * @extends module:org.geogig.web/org.geogig.web.model/RevisionObject
   * @param id {String} 
   * @param objectType {module:org.geogig.web/org.geogig.web.model/ObjectType} 
   * @param values {Array.<module:org.geogig.web/org.geogig.web.model/Value>} 
   */
  var exports = function(id, objectType, values) {
    var _this = this;
    RevisionObject.call(_this, id, objectType);
    _this['values'] = values;
  };

  /**
   * Constructs a <code>RevisionFeature</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:org.geogig.web/org.geogig.web.model/RevisionFeature} obj Optional instance to populate.
   * @return {module:org.geogig.web/org.geogig.web.model/RevisionFeature} The populated <code>RevisionFeature</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      RevisionObject.constructFromObject(data, obj);
      if (data.hasOwnProperty('values')) {
        obj['values'] = ApiClient.convertToType(data['values'], [Value]);
      }
    }
    return obj;
  }

  exports.prototype = Object.create(RevisionObject.prototype);
  exports.prototype.constructor = exports;

  /**
   * @member {Array.<module:org.geogig.web/org.geogig.web.model/Value>} values
   */
  exports.prototype['values'] = undefined;



  return exports;
}));


