/**
 * GeoGig Web API
 * GeoGig Web API.  You can find out more about GeoGig at [http://geogig.org](http://geogig.org)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: groldan@boundlessgeo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['org.geogig.web/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Geogig) {
      root.Geogig = {};
    }
    root.Geogig.SRS = factory(root.Geogig.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SRS model module.
   * @module org.geogig.web/org.geogig.web.model/SRS
   * @version 1.0-SNAPSHOT
   */

  /**
   * Constructs a new <code>SRS</code>.
   * @alias module:org.geogig.web/org.geogig.web.model/SRS
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>SRS</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:org.geogig.web/org.geogig.web.model/SRS} obj Optional instance to populate.
   * @return {module:org.geogig.web/org.geogig.web.model/SRS} The populated <code>SRS</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('wkt')) {
        obj['wkt'] = ApiClient.convertToType(data['wkt'], 'String');
      }
      if (data.hasOwnProperty('authorityCode')) {
        obj['authorityCode'] = ApiClient.convertToType(data['authorityCode'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} wkt
   */
  exports.prototype['wkt'] = undefined;
  /**
   * @member {String} authorityCode
   */
  exports.prototype['authorityCode'] = undefined;



  return exports;
}));


