/**
 * GeoGig Web API
 * GeoGig Web API.  You can find out more about GeoGig at [http://geogig.org](http://geogig.org)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: groldan@boundlessgeo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['org.geogig.web/ApiClient', 'org.geogig.web/org.geogig.web.model/Feature', 'org.geogig.web/org.geogig.web.model/FeatureFilter'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Feature'), require('./FeatureFilter'));
  } else {
    // Browser globals (root is window)
    if (!root.Geogig) {
      root.Geogig = {};
    }
    root.Geogig.UpdateFeaturesRequest = factory(root.Geogig.ApiClient, root.Geogig.Feature, root.Geogig.FeatureFilter);
  }
}(this, function(ApiClient, Feature, FeatureFilter) {
  'use strict';




  /**
   * The UpdateFeaturesRequest model module.
   * @module org.geogig.web/org.geogig.web.model/UpdateFeaturesRequest
   * @version 1.0-SNAPSHOT
   */

  /**
   * Constructs a new <code>UpdateFeaturesRequest</code>.
   * A request to update the featues matching the filter given by the query using the values given in the prototype feature
   * @alias module:org.geogig.web/org.geogig.web.model/UpdateFeaturesRequest
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>UpdateFeaturesRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:org.geogig.web/org.geogig.web.model/UpdateFeaturesRequest} obj Optional instance to populate.
   * @return {module:org.geogig.web/org.geogig.web.model/UpdateFeaturesRequest} The populated <code>UpdateFeaturesRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('prototype')) {
        obj['prototype'] = Feature.constructFromObject(data['prototype']);
      }
      if (data.hasOwnProperty('filter')) {
        obj['filter'] = FeatureFilter.constructFromObject(data['filter']);
      }
    }
    return obj;
  }

  /**
   * @member {module:org.geogig.web/org.geogig.web.model/Feature} prototype
   */
  exports.prototype['prototype'] = undefined;
  /**
   * @member {module:org.geogig.web/org.geogig.web.model/FeatureFilter} filter
   */
  exports.prototype['filter'] = undefined;



  return exports;
}));


