/**
 * GeoGig Web API
 * GeoGig Web API.  You can find out more about GeoGig at [http://geogig.org](http://geogig.org)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: groldan@boundlessgeo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['org.geogig.web/ApiClient', 'org.geogig.web/org.geogig.web.model/IdentifiedObject', 'org.geogig.web/org.geogig.web.model/UserInfoPrivateProfile', 'org.geogig.web/org.geogig.web.model/UserInfoPublicProfile', 'org.geogig.web/org.geogig.web.model/UserType'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./IdentifiedObject'), require('./UserInfoPrivateProfile'), require('./UserInfoPublicProfile'), require('./UserType'));
  } else {
    // Browser globals (root is window)
    if (!root.Geogig) {
      root.Geogig = {};
    }
    root.Geogig.UserInfo = factory(root.Geogig.ApiClient, root.Geogig.IdentifiedObject, root.Geogig.UserInfoPrivateProfile, root.Geogig.UserInfoPublicProfile, root.Geogig.UserType);
  }
}(this, function(ApiClient, IdentifiedObject, UserInfoPrivateProfile, UserInfoPublicProfile, UserType) {
  'use strict';




  /**
   * The UserInfo model module.
   * @module org.geogig.web/org.geogig.web.model/UserInfo
   * @version 1.0-SNAPSHOT
   */

  /**
   * Constructs a new <code>UserInfo</code>.
   * @alias module:org.geogig.web/org.geogig.web.model/UserInfo
   * @class
   * @implements module:org.geogig.web/org.geogig.web.model/IdentifiedObject
   * @param type {module:org.geogig.web/org.geogig.web.model/UserType} 
   * @param siteAdmin {Boolean} True if the user is a site administrator
   * @param publicProfile {module:org.geogig.web/org.geogig.web.model/UserInfoPublicProfile} 
   */
  var exports = function(type, siteAdmin, publicProfile) {
    var _this = this;

    IdentifiedObject.call(_this);
    _this['type'] = type;
    _this['siteAdmin'] = siteAdmin;
    _this['publicProfile'] = publicProfile;

  };

  /**
   * Constructs a <code>UserInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:org.geogig.web/org.geogig.web.model/UserInfo} obj Optional instance to populate.
   * @return {module:org.geogig.web/org.geogig.web.model/UserInfo} The populated <code>UserInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      IdentifiedObject.constructFromObject(data, obj);
      if (data.hasOwnProperty('type')) {
        obj['type'] = UserType.constructFromObject(data['type']);
      }
      if (data.hasOwnProperty('siteAdmin')) {
        obj['siteAdmin'] = ApiClient.convertToType(data['siteAdmin'], 'Boolean');
      }
      if (data.hasOwnProperty('publicProfile')) {
        obj['publicProfile'] = UserInfoPublicProfile.constructFromObject(data['publicProfile']);
      }
      if (data.hasOwnProperty('privateProfile')) {
        obj['privateProfile'] = UserInfoPrivateProfile.constructFromObject(data['privateProfile']);
      }
    }
    return obj;
  }

  /**
   * @member {module:org.geogig.web/org.geogig.web.model/UserType} type
   */
  exports.prototype['type'] = undefined;
  /**
   * True if the user is a site administrator
   * @member {Boolean} siteAdmin
   * @default false
   */
  exports.prototype['siteAdmin'] = false;
  /**
   * @member {module:org.geogig.web/org.geogig.web.model/UserInfoPublicProfile} publicProfile
   */
  exports.prototype['publicProfile'] = undefined;
  /**
   * @member {module:org.geogig.web/org.geogig.web.model/UserInfoPrivateProfile} privateProfile
   */
  exports.prototype['privateProfile'] = undefined;

  // Implement IdentifiedObject interface:
  /**
   * A unique and immutable identifier for the object, generated by the system, and unique across the whole system
   * @member {String} id
   */
exports.prototype['id'] = undefined;

  /**
   * A user given name for the object, unique across its domain of usage, and modifiable as long as it remains unique. I.e. Store and User names are globally unique, Repository names are unique in the scope of their owner.
   * @member {String} identity
   */
exports.prototype['identity'] = undefined;



  return exports;
}));


