/**
 * GeoGig Web API
 * GeoGig Web API.  You can find out more about GeoGig at [http://geogig.org](http://geogig.org)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: groldan@boundlessgeo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['org.geogig.web/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Geogig) {
      root.Geogig = {};
    }
    root.Geogig.ValueType = factory(root.Geogig.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';


  /**
   * Enum class ValueType.
   * @enum {}
   * @readonly
   */
  var exports = {
    /**
     * value: "null"
     * @const
     */
    "null": "null",
    /**
     * value: "BOOLEAN"
     * @const
     */
    "BOOLEAN": "BOOLEAN",
    /**
     * value: "BYTE"
     * @const
     */
    "BYTE": "BYTE",
    /**
     * value: "SHORT"
     * @const
     */
    "SHORT": "SHORT",
    /**
     * value: "INTEGER"
     * @const
     */
    "INTEGER": "INTEGER",
    /**
     * value: "LONG"
     * @const
     */
    "LONG": "LONG",
    /**
     * value: "FLOAT"
     * @const
     */
    "FLOAT": "FLOAT",
    /**
     * value: "DOUBLE"
     * @const
     */
    "DOUBLE": "DOUBLE",
    /**
     * value: "STRING"
     * @const
     */
    "STRING": "STRING",
    /**
     * value: "BOOLEAN_ARRAY"
     * @const
     */
    "BOOLEAN_ARRAY": "BOOLEAN_ARRAY",
    /**
     * value: "BYTE_ARRAY"
     * @const
     */
    "BYTE_ARRAY": "BYTE_ARRAY",
    /**
     * value: "SHORT_ARRAY"
     * @const
     */
    "SHORT_ARRAY": "SHORT_ARRAY",
    /**
     * value: "INTEGER_ARRAY"
     * @const
     */
    "INTEGER_ARRAY": "INTEGER_ARRAY",
    /**
     * value: "LONG_ARRAY"
     * @const
     */
    "LONG_ARRAY": "LONG_ARRAY",
    /**
     * value: "FLOAT_ARRAY"
     * @const
     */
    "FLOAT_ARRAY": "FLOAT_ARRAY",
    /**
     * value: "DOUBLE_ARRAY"
     * @const
     */
    "DOUBLE_ARRAY": "DOUBLE_ARRAY",
    /**
     * value: "STRING_ARRAY"
     * @const
     */
    "STRING_ARRAY": "STRING_ARRAY",
    /**
     * value: "POINT"
     * @const
     */
    "POINT": "POINT",
    /**
     * value: "LINESTRING"
     * @const
     */
    "LINESTRING": "LINESTRING",
    /**
     * value: "POLYGON"
     * @const
     */
    "POLYGON": "POLYGON",
    /**
     * value: "MULTIPOINT"
     * @const
     */
    "MULTIPOINT": "MULTIPOINT",
    /**
     * value: "MULTILINESTRING"
     * @const
     */
    "MULTILINESTRING": "MULTILINESTRING",
    /**
     * value: "MULTIPOLYGON"
     * @const
     */
    "MULTIPOLYGON": "MULTIPOLYGON",
    /**
     * value: "GEOMETRYCOLLECTION"
     * @const
     */
    "GEOMETRYCOLLECTION": "GEOMETRYCOLLECTION",
    /**
     * value: "GEOMETRY"
     * @const
     */
    "GEOMETRY": "GEOMETRY",
    /**
     * value: "UUID"
     * @const
     */
    "UUID": "UUID",
    /**
     * value: "BIG_INTEGER"
     * @const
     */
    "BIG_INTEGER": "BIG_INTEGER",
    /**
     * value: "BIG_DECIMAL"
     * @const
     */
    "BIG_DECIMAL": "BIG_DECIMAL",
    /**
     * value: "DATETIME"
     * @const
     */
    "DATETIME": "DATETIME",
    /**
     * value: "DATE"
     * @const
     */
    "DATE": "DATE",
    /**
     * value: "TIME"
     * @const
     */
    "TIME": "TIME",
    /**
     * value: "TIMESTAMP"
     * @const
     */
    "TIMESTAMP": "TIMESTAMP",
    /**
     * value: "MAP"
     * @const
     */
    "MAP": "MAP",
    /**
     * value: "CHAR"
     * @const
     */
    "CHAR": "CHAR",
    /**
     * value: "CHAR_ARRAY"
     * @const
     */
    "CHAR_ARRAY": "CHAR_ARRAY",
    /**
     * value: "ENVELOPE_2D"
     * @const
     */
    "ENVELOPE_2D": "ENVELOPE_2D"  };

  /**
   * Returns a <code>ValueType</code> enum value from a Javascript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:org.geogig.web/org.geogig.web.model/ValueType} The enum <code>ValueType</code> value.
   */
  exports.constructFromObject = function(object) {
    return object;
  }

  return exports;
}));


