/**
 * GeoGig Web API
 * GeoGig Web API.  You can find out more about GeoGig at [http://geogig.org](http://geogig.org)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: groldan@boundlessgeo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['org.geogig.web/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Geogig) {
      root.Geogig = {};
    }
    root.Geogig.VersionInfo = factory(root.Geogig.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The VersionInfo model module.
   * @module org.geogig.web/org.geogig.web.model/VersionInfo
   * @version 1.0-SNAPSHOT
   */

  /**
   * Constructs a new <code>VersionInfo</code>.
   * @alias module:org.geogig.web/org.geogig.web.model/VersionInfo
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>VersionInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:org.geogig.web/org.geogig.web.model/VersionInfo} obj Optional instance to populate.
   * @return {module:org.geogig.web/org.geogig.web.model/VersionInfo} The populated <code>VersionInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('version')) {
        obj['version'] = ApiClient.convertToType(data['version'], 'String');
      }
      if (data.hasOwnProperty('branch')) {
        obj['branch'] = ApiClient.convertToType(data['branch'], 'String');
      }
      if (data.hasOwnProperty('buildTime')) {
        obj['buildTime'] = ApiClient.convertToType(data['buildTime'], 'String');
      }
      if (data.hasOwnProperty('commitId')) {
        obj['commitId'] = ApiClient.convertToType(data['commitId'], 'String');
      }
      if (data.hasOwnProperty('commitTime')) {
        obj['commitTime'] = ApiClient.convertToType(data['commitTime'], 'String');
      }
      if (data.hasOwnProperty('commitMessage')) {
        obj['commitMessage'] = ApiClient.convertToType(data['commitMessage'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} version
   */
  exports.prototype['version'] = undefined;
  /**
   * @member {String} branch
   */
  exports.prototype['branch'] = undefined;
  /**
   * @member {String} buildTime
   */
  exports.prototype['buildTime'] = undefined;
  /**
   * @member {String} commitId
   */
  exports.prototype['commitId'] = undefined;
  /**
   * @member {String} commitTime
   */
  exports.prototype['commitTime'] = undefined;
  /**
   * @member {String} commitMessage
   */
  exports.prototype['commitMessage'] = undefined;



  return exports;
}));


