/**
 * GeoGig Web API
 * GeoGig Web API.  You can find out more about GeoGig at [http://geogig.org](http://geogig.org)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: groldan@boundlessgeo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RevisionFeatureType'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RevisionFeatureType'));
  } else {
    // Browser globals (root is window)
    if (!root.Geogig) {
      root.Geogig = {};
    }
    root.Geogig.Feature = factory(root.Geogig.ApiClient, root.Geogig.RevisionFeatureType);
  }
}(this, function(ApiClient, RevisionFeatureType) {
  'use strict';




  /**
   * The Feature model module.
   * @module model/Feature
   * @version 0.1-SNAPSHOT
   */

  /**
   * Constructs a new <code>Feature</code>.
   * type placeholder for a single feature. Server implementation dependent.
   * @alias module:model/Feature
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>Feature</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Feature} obj Optional instance to populate.
   * @return {module:model/Feature} The populated <code>Feature</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('featureType')) {
        obj['featureType'] = RevisionFeatureType.constructFromObject(data['featureType']);
      }
    }
    return obj;
  }

  /**
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {module:model/RevisionFeatureType} featureType
   */
  exports.prototype['featureType'] = undefined;



  return exports;
}));


