/**
 * GeoGig Web API
 * GeoGig Web API.  You can find out more about GeoGig at [http://geogig.org](http://geogig.org)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: groldan@boundlessgeo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Geogig) {
      root.Geogig = {};
    }
    root.Geogig.Ref = factory(root.Geogig.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Ref model module.
   * @module model/Ref
   * @version 0.1-SNAPSHOT
   */

  /**
   * Constructs a new <code>Ref</code>.
   * @alias module:model/Ref
   * @class
   * @param name {String} 
   * @param sha {String} 
   * @param sym {Boolean} 
   */
  var exports = function(name, sha, sym) {
    var _this = this;

    _this['name'] = name;
    _this['sha'] = sha;
    _this['sym'] = sym;

  };

  /**
   * Constructs a <code>Ref</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Ref} obj Optional instance to populate.
   * @return {module:model/Ref} The populated <code>Ref</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('sha')) {
        obj['sha'] = ApiClient.convertToType(data['sha'], 'String');
      }
      if (data.hasOwnProperty('sym')) {
        obj['sym'] = ApiClient.convertToType(data['sym'], 'Boolean');
      }
      if (data.hasOwnProperty('target')) {
        obj['target'] = ApiClient.convertToType(data['target'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} sha
   */
  exports.prototype['sha'] = undefined;
  /**
   * @member {Boolean} sym
   */
  exports.prototype['sym'] = undefined;
  /**
   * @member {String} target
   */
  exports.prototype['target'] = undefined;



  return exports;
}));


