/**
 * GeoGig Web API
 * GeoGig Web API.  You can find out more about GeoGig at [http://geogig.org](http://geogig.org)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: groldan@boundlessgeo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RepositoryInfo', 'model/TransactionStatus', 'model/UserInfo'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RepositoryInfo'), require('./TransactionStatus'), require('./UserInfo'));
  } else {
    // Browser globals (root is window)
    if (!root.Geogig) {
      root.Geogig = {};
    }
    root.Geogig.TransactionInfo = factory(root.Geogig.ApiClient, root.Geogig.RepositoryInfo, root.Geogig.TransactionStatus, root.Geogig.UserInfo);
  }
}(this, function(ApiClient, RepositoryInfo, TransactionStatus, UserInfo) {
  'use strict';




  /**
   * The TransactionInfo model module.
   * @module model/TransactionInfo
   * @version 0.1-SNAPSHOT
   */

  /**
   * Constructs a new <code>TransactionInfo</code>.
   * 
   * @alias module:model/TransactionInfo
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>TransactionInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TransactionInfo} obj Optional instance to populate.
   * @return {module:model/TransactionInfo} The populated <code>TransactionInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = TransactionStatus.constructFromObject(data['status']);
      }
      if (data.hasOwnProperty('created-at')) {
        obj['created-at'] = ApiClient.convertToType(data['created-at'], 'Date');
      }
      if (data.hasOwnProperty('created-by')) {
        obj['created-by'] = UserInfo.constructFromObject(data['created-by']);
      }
      if (data.hasOwnProperty('terminated-at')) {
        obj['terminated-at'] = ApiClient.convertToType(data['terminated-at'], 'Date');
      }
      if (data.hasOwnProperty('terminated-by')) {
        obj['terminated-by'] = UserInfo.constructFromObject(data['terminated-by']);
      }
      if (data.hasOwnProperty('repository')) {
        obj['repository'] = RepositoryInfo.constructFromObject(data['repository']);
      }
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {module:model/TransactionStatus} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {Date} created-at
   */
  exports.prototype['created-at'] = undefined;
  /**
   * @member {module:model/UserInfo} created-by
   */
  exports.prototype['created-by'] = undefined;
  /**
   * @member {Date} terminated-at
   */
  exports.prototype['terminated-at'] = undefined;
  /**
   * @member {module:model/UserInfo} terminated-by
   */
  exports.prototype['terminated-by'] = undefined;
  /**
   * @member {module:model/RepositoryInfo} repository
   */
  exports.prototype['repository'] = undefined;



  return exports;
}));


