/**
 * GeoGig Web API
 * GeoGig Web API.  You can find out more about GeoGig at [http://geogig.org](http://geogig.org)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: groldan@boundlessgeo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/IdentifiedObject'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./IdentifiedObject'));
  } else {
    // Browser globals (root is window)
    if (!root.Geogig) {
      root.Geogig = {};
    }
    root.Geogig.UserInfoPrivateProfile = factory(root.Geogig.ApiClient, root.Geogig.IdentifiedObject);
  }
}(this, function(ApiClient, IdentifiedObject) {
  'use strict';




  /**
   * The UserInfoPrivateProfile model module.
   * @module model/UserInfoPrivateProfile
   * @version 0.1-SNAPSHOT
   */

  /**
   * Constructs a new <code>UserInfoPrivateProfile</code>.
   * @alias module:model/UserInfoPrivateProfile
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>UserInfoPrivateProfile</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserInfoPrivateProfile} obj Optional instance to populate.
   * @return {module:model/UserInfoPrivateProfile} The populated <code>UserInfoPrivateProfile</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('fullName')) {
        obj['fullName'] = ApiClient.convertToType(data['fullName'], 'String');
      }
      if (data.hasOwnProperty('emailAddress')) {
        obj['emailAddress'] = ApiClient.convertToType(data['emailAddress'], 'String');
      }
      if (data.hasOwnProperty('created_at')) {
        obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
      }
      if (data.hasOwnProperty('updated_at')) {
        obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
      }
      if (data.hasOwnProperty('location')) {
        obj['location'] = ApiClient.convertToType(data['location'], 'String');
      }
      if (data.hasOwnProperty('defaultStore')) {
        obj['defaultStore'] = IdentifiedObject.constructFromObject(data['defaultStore']);
      }
      if (data.hasOwnProperty('additionalStores')) {
        obj['additionalStores'] = ApiClient.convertToType(data['additionalStores'], [IdentifiedObject]);
      }
    }
    return obj;
  }

  /**
   * User's full name, as used for commit info
   * @member {String} fullName
   */
  exports.prototype['fullName'] = undefined;
  /**
   * Default user email address, as used in commit info
   * @member {String} emailAddress
   */
  exports.prototype['emailAddress'] = undefined;
  /**
   * @member {Date} created_at
   */
  exports.prototype['created_at'] = undefined;
  /**
   * @member {Date} updated_at
   */
  exports.prototype['updated_at'] = undefined;
  /**
   * Human readable location name.
   * @member {String} location
   */
  exports.prototype['location'] = undefined;
  /**
   * @member {module:model/IdentifiedObject} defaultStore
   */
  exports.prototype['defaultStore'] = undefined;
  /**
   * @member {Array.<module:model/IdentifiedObject>} additionalStores
   */
  exports.prototype['additionalStores'] = undefined;



  return exports;
}));


