/*
 * GeoGig Web API
 * GeoGig Web API.  You can find out more about GeoGig at [http://geogig.org](http://geogig.org)
 *
 * OpenAPI spec version: 0.1.0
 * Contact: groldan@boundlessgeo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.geogig.server.model;

import java.time.OffsetDateTime;
import java.util.UUID;

import javax.persistence.Entity;
import javax.persistence.Id;

import lombok.Data;
import lombok.NoArgsConstructor;

public @Entity @Data @NoArgsConstructor class AsyncTask {

    public static enum Status {
        SCHEDULED, RUNNING, COMPLETE, FAILED, ABORTING, ABORTED
    };

    private @Id UUID id;

    private Status status;

    private String description;

    private OffsetDateTime lastUpdated;

    private OffsetDateTime scheduledAt;

    private OffsetDateTime startedAt;

    private OffsetDateTime finishedAt;

    private UUID repository;

    private UUID startedByUserId;

    private UUID abortedByUserId;

    private UUID transactionId;

    private String errorMessage;
}
